# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daan/CLionProjects/silver_shark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daan/CLionProjects/silver_shark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daan/CLionProjects/silver_shark/CMakeFiles /home/daan/CLionProjects/silver_shark//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daan/CLionProjects/silver_shark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named silver_shark

# Build rule for target.
silver_shark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silver_shark
.PHONY : silver_shark

# fast build rule for target.
silver_shark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/build
.PHONY : silver_shark/fast

#=============================================================================
# Target rules for targets named silver_shark_autogen_timestamp_deps

# Build rule for target.
silver_shark_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silver_shark_autogen_timestamp_deps
.PHONY : silver_shark_autogen_timestamp_deps

# fast build rule for target.
silver_shark_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark_autogen_timestamp_deps.dir/build.make CMakeFiles/silver_shark_autogen_timestamp_deps.dir/build
.PHONY : silver_shark_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named silver_shark_autogen

# Build rule for target.
silver_shark_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silver_shark_autogen
.PHONY : silver_shark_autogen

# fast build rule for target.
silver_shark_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark_autogen.dir/build.make CMakeFiles/silver_shark_autogen.dir/build
.PHONY : silver_shark_autogen/fast

silver_shark_autogen/mocs_compilation.o: silver_shark_autogen/mocs_compilation.cpp.o
.PHONY : silver_shark_autogen/mocs_compilation.o

# target to build an object file
silver_shark_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/silver_shark_autogen/mocs_compilation.cpp.o
.PHONY : silver_shark_autogen/mocs_compilation.cpp.o

silver_shark_autogen/mocs_compilation.i: silver_shark_autogen/mocs_compilation.cpp.i
.PHONY : silver_shark_autogen/mocs_compilation.i

# target to preprocess a source file
silver_shark_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/silver_shark_autogen/mocs_compilation.cpp.i
.PHONY : silver_shark_autogen/mocs_compilation.cpp.i

silver_shark_autogen/mocs_compilation.s: silver_shark_autogen/mocs_compilation.cpp.s
.PHONY : silver_shark_autogen/mocs_compilation.s

# target to generate assembly for a file
silver_shark_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/silver_shark_autogen/mocs_compilation.cpp.s
.PHONY : silver_shark_autogen/mocs_compilation.cpp.s

src/engine/data.o: src/engine/data.cpp.o
.PHONY : src/engine/data.o

# target to build an object file
src/engine/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/data.cpp.o
.PHONY : src/engine/data.cpp.o

src/engine/data.i: src/engine/data.cpp.i
.PHONY : src/engine/data.i

# target to preprocess a source file
src/engine/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/data.cpp.i
.PHONY : src/engine/data.cpp.i

src/engine/data.s: src/engine/data.cpp.s
.PHONY : src/engine/data.s

# target to generate assembly for a file
src/engine/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/data.cpp.s
.PHONY : src/engine/data.cpp.s

src/engine/graph/graph.o: src/engine/graph/graph.cpp.o
.PHONY : src/engine/graph/graph.o

# target to build an object file
src/engine/graph/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/graph/graph.cpp.o
.PHONY : src/engine/graph/graph.cpp.o

src/engine/graph/graph.i: src/engine/graph/graph.cpp.i
.PHONY : src/engine/graph/graph.i

# target to preprocess a source file
src/engine/graph/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/graph/graph.cpp.i
.PHONY : src/engine/graph/graph.cpp.i

src/engine/graph/graph.s: src/engine/graph/graph.cpp.s
.PHONY : src/engine/graph/graph.s

# target to generate assembly for a file
src/engine/graph/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/graph/graph.cpp.s
.PHONY : src/engine/graph/graph.cpp.s

src/engine/string_id_table.o: src/engine/string_id_table.cpp.o
.PHONY : src/engine/string_id_table.o

# target to build an object file
src/engine/string_id_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/string_id_table.cpp.o
.PHONY : src/engine/string_id_table.cpp.o

src/engine/string_id_table.i: src/engine/string_id_table.cpp.i
.PHONY : src/engine/string_id_table.i

# target to preprocess a source file
src/engine/string_id_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/string_id_table.cpp.i
.PHONY : src/engine/string_id_table.cpp.i

src/engine/string_id_table.s: src/engine/string_id_table.cpp.s
.PHONY : src/engine/string_id_table.s

# target to generate assembly for a file
src/engine/string_id_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/engine/string_id_table.cpp.s
.PHONY : src/engine/string_id_table.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/graph/machine_node_item.o: src/ui/graph/machine_node_item.cpp.o
.PHONY : src/ui/graph/machine_node_item.o

# target to build an object file
src/ui/graph/machine_node_item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/machine_node_item.cpp.o
.PHONY : src/ui/graph/machine_node_item.cpp.o

src/ui/graph/machine_node_item.i: src/ui/graph/machine_node_item.cpp.i
.PHONY : src/ui/graph/machine_node_item.i

# target to preprocess a source file
src/ui/graph/machine_node_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/machine_node_item.cpp.i
.PHONY : src/ui/graph/machine_node_item.cpp.i

src/ui/graph/machine_node_item.s: src/ui/graph/machine_node_item.cpp.s
.PHONY : src/ui/graph/machine_node_item.s

# target to generate assembly for a file
src/ui/graph/machine_node_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/machine_node_item.cpp.s
.PHONY : src/ui/graph/machine_node_item.cpp.s

src/ui/graph/port_item.o: src/ui/graph/port_item.cpp.o
.PHONY : src/ui/graph/port_item.o

# target to build an object file
src/ui/graph/port_item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/port_item.cpp.o
.PHONY : src/ui/graph/port_item.cpp.o

src/ui/graph/port_item.i: src/ui/graph/port_item.cpp.i
.PHONY : src/ui/graph/port_item.i

# target to preprocess a source file
src/ui/graph/port_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/port_item.cpp.i
.PHONY : src/ui/graph/port_item.cpp.i

src/ui/graph/port_item.s: src/ui/graph/port_item.cpp.s
.PHONY : src/ui/graph/port_item.s

# target to generate assembly for a file
src/ui/graph/port_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/graph/port_item.cpp.s
.PHONY : src/ui/graph/port_item.cpp.s

src/ui/main_window.o: src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.o

# target to build an object file
src/ui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.cpp.o

src/ui/main_window.i: src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.i

# target to preprocess a source file
src/ui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.cpp.i

src/ui/main_window.s: src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.s

# target to generate assembly for a file
src/ui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silver_shark.dir/build.make CMakeFiles/silver_shark.dir/src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... silver_shark_autogen"
	@echo "... silver_shark_autogen_timestamp_deps"
	@echo "... silver_shark"
	@echo "... silver_shark_autogen/mocs_compilation.o"
	@echo "... silver_shark_autogen/mocs_compilation.i"
	@echo "... silver_shark_autogen/mocs_compilation.s"
	@echo "... src/engine/data.o"
	@echo "... src/engine/data.i"
	@echo "... src/engine/data.s"
	@echo "... src/engine/graph/graph.o"
	@echo "... src/engine/graph/graph.i"
	@echo "... src/engine/graph/graph.s"
	@echo "... src/engine/string_id_table.o"
	@echo "... src/engine/string_id_table.i"
	@echo "... src/engine/string_id_table.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/graph/machine_node_item.o"
	@echo "... src/ui/graph/machine_node_item.i"
	@echo "... src/ui/graph/machine_node_item.s"
	@echo "... src/ui/graph/port_item.o"
	@echo "... src/ui/graph/port_item.i"
	@echo "... src/ui/graph/port_item.s"
	@echo "... src/ui/main_window.o"
	@echo "... src/ui/main_window.i"
	@echo "... src/ui/main_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

